name: chrome-extension CI

on:
  push:
    branches: [main]
    paths:
      - "extensions/chrome_v1/**"
  pull_request:
    branches: [main]
    paths:
      - "extensions/chrome_v1/**"

defaults:
  run:
    working-directory: ./extensions/chrome_v1

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run ESLint and format fix
        run: bun run fix

      - name: Run markdown lint
        # DON't TOUCH THIS LINE BELOW #
        run: bunx markdownlint-cli2 "./**/*.md" --config .markdownlint-cli2.jsonc

  test-and-build:
    needs: lint-and-format
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun test

      - name: Build extension
        run: bun run build

      - name: Zip Extension
        run: zip -r chrome-extension.zip dist/

      - name: Generate version
        id: version
        run: echo "version=$(date +'%Y.%m.%d.%H%M')" >> $GITHUB_OUTPUT

      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.version.outputs.version }}
          tag_name: v${{ steps.version.outputs.version }}
          files: extensions/chrome_v1/chrome-extension.zip
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
