name: chrome-extension CI

on:
  push:
    branches: [main]
    paths:
      - "extensions/chrome_v1/**"
  pull_request:
    branches: [main]
    paths:
      - "extensions/chrome_v1/**"

defaults:
  run:
    working-directory: ./extensions/chrome_v1

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run ESLint
        run: bun run lint

      - name: Check formatting
        run: bunx prettier --check .

      - name: Run markdown lint
        run: bunx markdownlint-cli2 "./**/*.md" --config .markdownlint-cli2.jsonc

  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun test

      - name: Build extension
        run: bun run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: chrome-extension
          path: extensions/chrome_v1/dist/
          if-no-files-found: error
